--Procedimientos 
--Un procedimiento almacenado para registrar una venta.
--Validar que el cliente exista.
--Verificar que el stock sea suficiente antes de procesar la venta.
--Si no hay stock suficiente, Notificar por medio de un mensaje en consola usando RAISE.
--Si hay stock, se realiza el registro de la venta.